name:                attoparsec-uri
version:             0.0.9
github:              "athanclark/attoparsec-uri"
license:             BSD3
author:              "Athan Clark"
maintainer:          "athan.clark@gmail.com"
copyright:           "Copyright (c) 2023 Athan Clark"

extra-source-files:
- README.md

# Metadata used when publishing your package
synopsis:            URI parser / printer using attoparsec
category:            Web

description:         Please see the README on GitHub at <https://github.com/athanclark/attoparsec-uri#readme>

ghc-options:
  - -Wall

dependencies:
- base >= 4.11 && < 5
- attoparsec
- bytedump
- ip >= 1.4.0
- strict
- text
- QuickCheck
- quickcheck-instances
- vector

library:
  source-dirs: src

tests:
  attoparsec-uri-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - attoparsec-uri
    - tasty
    - tasty-quickcheck
    - QuickCheck
    - attoparsec
    - text
